### ISSUE TITLE
Is it alive ?

### ISSUE THREAD

**Issue by marcoturi** [modella/modella#50]
Is Modella still alive and maintained ? Or there are alternatives that took place ? Thank you :)

**Comment by matthewmueller** [comment]
sorry, but not really. should still work, but i'm convinced ORMs are an anti-pattern at this point, unless it's purely for rapid prototyping.

**Comment by vendethiel** [comment]
Not sure something that doesn't deal at all with the "relational mapping" part can be called an ORM, or are you talking about specific plugins? Modella itself only deals with the objects...
